#!/usr/bin/env node

// One-shot icon component generator (issue #53): reads the r7 icon dump
// (docs/research/assets/r7/icons.json, 218 entries / 64 unique raw
// markups) and emits one typed React SVG component per unique normalized
// markup into apps/web/src/icons/. Normalization drops width/height/class,
// so size and text-color class variants of the same glyph collapse: 64
// raw → 41 components, each defaulting to its first-seen size (callers
// override via the width/height props). The NAME_TABLE below maps each
// normalized markup to a semantic component name; an unmapped markup
// fails the run so any new baseline icon forces an explicit naming
// decision.

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ICONS_JSON = 'docs/research/assets/r7/icons.json';
const OUT_DIR = 'apps/web/src/icons';

/** Attr names JSX renders in camelCase. */
const CAMEL = {
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-miterlimit': 'strokeMiterlimit',
  'fill-rule': 'fillRule',
  'clip-rule': 'clipRule',
};

const ATTR_RE = /([a-zA-Z0-9-]+)="([^"]*)"/g;

function parseAttrs(str) {
  const attrs = [];
  for (const m of str.matchAll(ATTR_RE)) {
    attrs.push([m[1], m[2]]);
  }
  return attrs;
}

/** Root svg: keep everything except width/height/class. */
function rootAttrs(svg) {
  const open = svg.match(/^<svg\s+([^>]*)>/);
  if (open == null) throw new Error('not an svg element');
  return parseAttrs(open[1]).filter(([k]) => k !== 'width' && k !== 'height' && k !== 'class');
}

/** Inner children markup, verbatim. */
function innerMarkup(svg) {
  const open = svg.match(/^<svg\s+[^>]*>/);
  return svg.slice(open[0].length, -6);
}

/** Attr list → JSX attribute string (drops class, camelCase hyphens). */
function attrsToJsx(attrs) {
  return attrs
    .filter(([k]) => k !== 'class')
    .map(([k, v]) => (CAMEL[k] ? `${CAMEL[k]}="${v}"` : `${k}="${v}"`))
    .join(' ');
}

/** JSX-ify a child element: camelCase hyphenated attr names, drop class. */
function toJsx(element) {
  const m = element.match(/^<([a-zA-Z]+)\s*([^>]*?)\/?>/);
  if (m == null) throw new Error(`unparsable element: ${element}`);
  const [, tag, attrStr] = m;
  const attrs = attrsToJsx(parseAttrs(attrStr));
  return `<${tag}${attrs ? ` ${attrs}` : ''} />`;
}

function normalize(svg) {
  const children = innerMarkup(svg)
    // outerHTML keeps explicit closing tags; collapse to self-closing form
    .replace(/<\/[a-zA-Z]+>/g, '')
    .split(/(?=<[a-zA-Z])/)
    .filter((s) => s.trim() !== '')
    .map((s) => toJsx(s.trim()));
  return { attrs: rootAttrs(svg), children };
}

const entries = JSON.parse(readFileSync(ICONS_JSON, 'utf8'));
const uniq = new Map(); // normalized markup string -> { attrs, children, size, contexts }
for (const e of entries) {
  const n = normalize(e.svg);
  const key = JSON.stringify([n.attrs, n.children]);
  if (!uniq.has(key)) {
    uniq.set(key, { ...n, size: [e.w, e.h], count: 0, contexts: [] });
  }
  const u = uniq.get(key);
  u.count += 1;
  u.contexts.push(e.context ?? e.route);
}

const sorted = [...uniq.entries()].sort((a, b) => b[1].count - a[1].count);

if (process.argv.includes('--list')) {
  for (const [key, u] of sorted) {
    const hash = createHash('sha1').update(key).digest('hex').slice(0, 10);
    console.log(
      `#${hash} size=${u.size} count=${u.count} ctx=${u.contexts.slice(0, 2).join(' | ')}`,
    );
    console.log(`  attrs: ${attrsToJsx(u.attrs)}`);
    console.log(`  children: ${u.children.join(' ')}`);
  }
  process.exit(0);
}

const NAME_TABLE = JSON.parse(readFileSync(new URL('./icon-names.json', import.meta.url), 'utf8'));

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const usedNames = new Set();
const exports = [];
for (const [key, u] of sorted) {
  const hash = createHash('sha1').update(key).digest('hex').slice(0, 10);
  const name = NAME_TABLE[hash];
  if (name == null) {
    console.error(`unmapped icon markup #${hash} — add to scripts/icon-names.json`);
    console.error(`  contexts: ${u.contexts.join(' | ')}`);
    console.error(`  children: ${u.children.join(' ')}`);
    process.exit(1);
  }
  const pascal = name[0].toUpperCase() + name.slice(1);
  if (usedNames.has(pascal)) throw new Error(`duplicate component name ${pascal}`);
  usedNames.add(pascal);

  const [w, h] = u.size;
  const file = `// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#${hash}, seen ${u.count}×: ${u.contexts.slice(0, 3).join(' | ')}). Do not edit.
import type { SVGProps } from 'react';

export function ${pascal}({ width = ${w}, height = ${h}, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg aria-hidden="true" width={width} height={height} ${attrsToJsx(u.attrs)} {...props}>
${u.children.map((c) => `      ${c}`).join('\n')}
    </svg>
  );
}
`;
  writeFileSync(join(OUT_DIR, `${name}.tsx`), file);
  exports.push(`export { ${pascal} } from './${name}.js';`);
}

writeFileSync(
  join(OUT_DIR, 'index.ts'),
  `// Generated by scripts/generate-icons.mjs. Do not edit.
${exports.sort().join('\n')}
`,
);

// emit Biome-stable formatting so regeneration keeps `biome ci` green
const formatted = spawnSync('pnpm', ['exec', 'biome', 'check', '--write', OUT_DIR], {
  encoding: 'utf8',
});
if (formatted.status !== 0) {
  console.error(`biome check --write failed:\n${formatted.stdout}\n${formatted.stderr}`);
  process.exit(1);
}

console.log(`wrote ${usedNames.size} icon components to ${OUT_DIR}`);
