#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# #263 npm 首发人肉向导（06 册 §11 W2-D4/D5；本票只交脚本，真正首发跑 #266）。
# 形态：账号确认 → 2FA → granular token → 两包 publish 顺序引导 → 干净环境
# npx 全链验收 → 收尾处置。token 纪律：只进 env（read -rs 采集 + argv 传参），
# 不写 .env / .npmrc / 任何盘——本向导零 write_env / 零 set_secret。
# 不自动 publish：发布命令打印给人肉在自己终端跑，向导只做引导、值采集与
# 只读校验（whoami / npm view / curl）。前置守卫：#261（主包整形）与 #262
# （cli 改名）未落地时，发布段与验收段运行时熔断并指路。
# npm 事实依据（docs.npmjs.com，2026-09-25 查证）：2025-11 起仅存 granular
# token；发布需账号 2FA 或 bypass token；bypass 直发 2027-01 移除——故推荐
# 账号 2FA + token 不勾 bypass + publish 交互 OTP。

TOTAL_STAGES=6

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO_ROOT"

banner "pacman · npm 首发 0.1.0（@xiechimon 两包）"

# ── Stage 1: npm 账号确认 ─────────────────────────────────────────────────
stage "npm 账号确认"
say "确认发布者 npm 账号登录态。向导只跑只读命令（npm whoami），不代登录。"
command -v npm >/dev/null 2>&1 || { warn "npm 不在 PATH——先装 Node 22/24 LTS 再回来重跑"; exit 1; }
NPM_USERNAME=""
LOGIN_TRIES=0
while [[ -z "$NPM_USERNAME" ]]; do
  NPM_USERNAME=$(npm whoami 2>/dev/null </dev/null || true)
  if [[ -z "$NPM_USERNAME" ]]; then
    (( LOGIN_TRIES >= 5 )) && { warn "连续 5 次未登录——退出，登录后重跑向导。"; exit 1; }
    LOGIN_TRIES=$((LOGIN_TRIES + 1))
    warn "当前环境未登录 npm（npm whoami 无人）。"
    say "另开一个终端跑 npm login（浏览器完成登录），然后回到这里。"
    pause "登录完成后回车，我重新验证"
  fi
done
printf '  %s✓ 已登录：%s%s\n' "$GREEN" "$NPM_USERNAME" "$RESET"
open_url "https://www.npmjs.com/~${NPM_USERNAME}"
note "确认头像与用户名无误——两包都会挂在这个账号的 scope 下。"
note "本向导不落盘任何值：Ctrl-C 中断后重跑等于从头来（token 要重新粘贴）。"

# ── Stage 2: 2FA 状态 ─────────────────────────────────────────────────────
stage "2FA 状态"
say "npm 现行规则：发布要么账号 2FA 已启用，要么 token 勾 bypass——本向导走前者。"
open_url "https://www.npmjs.com/settings/${NPM_USERNAME}/tfa"
step "直达 404 就走菜单：右上头像 → Account → Two-Factor Authentication。"
step "已启用：看到已绑定的验证器 / 安全密钥即可，本阶段完成。"
step "未启用：Enable 2FA → 输账号密码 → 选验证器（TOTP）或安全密钥。"
warn "恢复码（recovery codes）务必存进密码管理器：用恢复码登录会触发 72 小时"
warn "发布 / 建 token 冻结——首发当天踩到就是硬停。"
step "验证器（TOTP）比纯安全密钥顺：publish 的 OTP 提示要 6 位数字码。"
pause "在页面上确认完 2FA 状态后回车"
PROFILE_2FA=$(npm profile get </dev/null 2>/dev/null | grep -i "two-factor" || true)
if [[ -n "$PROFILE_2FA" && "$PROFILE_2FA" != *"none"* ]]; then
  printf '  %s✓ npm profile get：%s%s\n' "$GREEN" "$PROFILE_2FA" "$RESET"
else
  warn "npm profile get 没读到已启用的 2FA（或命令不可用），以页面显示为准。"
fi
confirm "账号 2FA 已启用？" || warn "没有 2FA 就无法按本流程发布；去开完再回来重跑"

# ── Stage 3: granular access token（只进 env，不落盘）─────────────────────
stage "granular access token（只进 env，不落盘）"
say "建一枚首发专用 granular token：scope 尽量限 @xiechimon，短期过期。"
open_url "https://www.npmjs.com/settings/${NPM_USERNAME}/tokens/granular-access-tokens/new"
step "直达失败走菜单：头像 → Access Tokens → Generate New Token（若出现类型"
step "选择，选 Granular——2025-11 起经典 token 已移除，只剩这一种）。"
step "Token name：pacman-first-publish-0.1.0。"
step "Packages and scopes → Permissions：Read and write (publish and stage)。"
step "Select Packages → 先试 Only select packages and scopes，搜 @xiechimon。"
say "首发前 scope 名下还没有包，选择器多半搜不到它——退路（官方文档同款建议）："
say "选 All Packages + 过期压到 7 天，首发完成立刻删掉，需要时再建收窄 token。"
step "Bypass two-factor authentication：保持不勾——账号 2FA 已开，publish 时"
step "交互输 OTP 即可；bypass 直发 2027-01 将被 npm 移除，不把首发押在它上。"
step "Expiration：7 天（首发窗口，兜底泄露面）。"
step "Generate Token → 在页面顶部复制 token（只显示这一次，关页即永别）。"
TOKEN_TRIES=0
while :; do
  ask_secret NPM_PUBLISH_TOKEN "粘贴 token（npm_ 开头）："
  if [[ "$NPM_PUBLISH_TOKEN" == npm_* && ${#NPM_PUBLISH_TOKEN} -gt 20 ]]; then
    break
  fi
  (( TOKEN_TRIES >= 5 )) && { warn "连续 5 次没粘对——放弃 token 采集，发布回退 npm login 会话。"; NPM_PUBLISH_TOKEN=""; break; }
  TOKEN_TRIES=$((TOKEN_TRIES + 1))
  warn "不像 granular token（npm_ 前缀 + 长串）；重新粘贴一次。"
done
TOKEN_WHOAMI=$(npm whoami --//registry.npmjs.org/:_authToken="$NPM_PUBLISH_TOKEN" </dev/null 2>/dev/null || true)
if [[ "$TOKEN_WHOAMI" == "$NPM_USERNAME" ]]; then
  printf '  %s✓ token 身份校验通过（whoami = %s）%s\n' "$GREEN" "$NPM_USERNAME" "$RESET"
else
  warn "token 没通过 whoami——granular token 未必有权访问身份端点，不必然无效；"
  warn "终极校验在 publish 那一刻。若 publish 报 E401，先怀疑 token 抄错或过期。"
fi
note "token 只活在本向导进程与你的终端 env 里：没写 .env、没写 .npmrc、"
note "没进 shell history。重跑向导要重新粘贴（或重新生成一枚）。"

# ── Stage 4: 首发执行（两包顺序，人肉位）──────────────────────────────────
stage "首发执行（主包先、cli 包后；发布命令在你的终端跑）"
say "先做前置自检（只读）：包整形、registry 状态、工作区干净度。"
PKG_DIRS=( "apps/server" "apps/daemon" )
PKG_NAMES=( "@xiechimon/pacman" "@xiechimon/pacman-cli" )
PKG_HINTS=( "#261 主包整形" "#262 cli 改名" )
PUBLISH_READY=1
TO_PUBLISH=()
if [[ -n "$(git status --porcelain 2>/dev/null || true)" ]]; then
  warn "git 工作区不干净——npm publish 按磁盘文件打包，未提交改动会进包。"
  say "先提交或收掉再发布（向导只提醒，不代处理）。"
fi
for i in 0 1; do
  dir="${PKG_DIRS[$i]}" name="${PKG_NAMES[$i]}" hint="${PKG_HINTS[$i]}" mf="$dir/package.json"
  if [[ ! -f "$mf" ]]; then
    warn "$mf 不存在（$hint 未落地？）"; PUBLISH_READY=0; continue
  fi
  actual=$(node -p "JSON.parse(require('fs').readFileSync('$mf','utf8')).name" 2>/dev/null || true)
  if [[ "$actual" != "$name" ]]; then
    warn "$dir 包名仍是「${actual:-（读不到）}」，应为 $name——$hint 未落地。"
    PUBLISH_READY=0
  fi
  is_private=$(node -p "JSON.parse(require('fs').readFileSync('$mf','utf8')).private === true" 2>/dev/null || true)
  if [[ "$is_private" == "true" ]]; then
    warn "$dir 仍是 private: true——npm 会拒发。"; PUBLISH_READY=0
  fi
  version=$(node -p "JSON.parse(require('fs').readFileSync('$mf','utf8')).version || '未设'" 2>/dev/null || true)
  if [[ "$version" != "0.1.0" ]]; then
    warn "$dir 版本是 ${version:-（读不到）}，首发口径 0.1.0——确认后再继续。"
  fi
  access=$(node -p "(JSON.parse(require('fs').readFileSync('$mf','utf8')).publishConfig || {}).access || ''" 2>/dev/null || true)
  if [[ "$access" != "public" ]]; then
    warn "$dir 缺 publishConfig.access=public——命令里会带 --access public 兜底。"
  fi
  ws_deps=$(node -p "Object.entries(JSON.parse(require('fs').readFileSync('$mf','utf8')).dependencies || {}).filter(([,v]) => /workspace:|catalog:/.test(String(v))).map(([k,v]) => k+'@'+v).join(', ')" 2>/dev/null || true)
  if [[ -n "$ws_deps" ]]; then
    warn "$dir dependencies 仍带 workspace:/catalog: 引用（$ws_deps）——"
    warn "npm publish 会原样打进 manifest，装包装不上。整形（$hint）没完成。"
    PUBLISH_READY=0
  fi
  files_field=$(node -p "JSON.stringify(JSON.parse(require('fs').readFileSync('$mf','utf8')).files || null)" 2>/dev/null || true)
  if [[ "$files_field" == "null" ]]; then
    warn "$dir 无 files 字段——默认全目录打包（能发但肥），确认整形预期。"
  fi
  has_build=$(node -p "Object.hasOwn(JSON.parse(require('fs').readFileSync('$mf','utf8')), 'scripts') && Object.hasOwn(JSON.parse(require('fs').readFileSync('$mf','utf8')).scripts || {}, 'build')" 2>/dev/null || true)
  if [[ "$has_build" == "true" ]]; then
    note "$dir 有 build script——发布前先 pnpm -C $dir build 保证产物新鲜。"
  fi
  reg_v=$(npm view "$name" version </dev/null 2>/dev/null || true)
  if [[ -z "$reg_v" ]]; then
    TO_PUBLISH+=("$i")
    note "registry 尚无 $name——首发位。"
  elif [[ "$reg_v" == "0.1.0" ]]; then
    note "$name@0.1.0 已在 registry（断点续跑：跳过此包）。"
  else
    warn "$name 在 registry 已有版本 $reg_v——不是首发口径，人工裁决后再继续。"
  fi
done
if (( PUBLISH_READY )); then
  say "发布顺序：@xiechimon/pacman（主包，内嵌 web，npx 主路径）先发，"
  say "@xiechimon/pacman-cli 后发——两包互不依赖，顺序只让验收链尽早可测。"
  say "以下命令在你自己的终端逐行跑（不是这里）；token 以变量引用进命令，"
  say "不落 shell history。先让 token 进当前 shell："
  if [[ -z "${NPM_PUBLISH_TOKEN:-}" ]]; then
    warn "token 未采集成功：以下命令去掉 --//registry… 参数，走 npm login 会话直发（OTP 照常）。"
  fi
  step "bash/zsh：cd $REPO_ROOT && read -rs NPM_PUBLISH_TOKEN && export NPM_PUBLISH_TOKEN"
  step "fish：cd $REPO_ROOT; and read -s NPM_PUBLISH_TOKEN; and set -x NPM_PUBLISH_TOKEN \$NPM_PUBLISH_TOKEN"
  note "read 粘贴后回车（不回显）；token 在页面生成后如果还没复制，现在回去复制。"
  if [[ ${#TO_PUBLISH[@]} -gt 0 ]]; then
    for i in "${TO_PUBLISH[@]}"; do
      step "cd ${PKG_DIRS[$i]} && npm publish --access public --//registry.npmjs.org/:_authToken=\"\$NPM_PUBLISH_TOKEN\""
    done
  else
    note "两包均已在册——无待发命令，直接进 registry 复核。"
  fi
  say "每包 publish 都可能问一次 OTP（账号 2FA + token 未勾 bypass）："
  say "验证器 6 位码照输即可，这就是双保险，不是故障。"
  note "token 只以参数形态短暂出现在本机进程列表（ps）；命令里引用的是变量名，"
  note "不会进 history。npm 会把 + @xiechimon/…@0.1.0 打到输出，那就是成功。"
  pause "两包都发完（或断点续跑已齐）后回车，我去 registry 复核"
  V1="" V2=""
  for round in 1 2 3; do
    V1=$(npm view "${PKG_NAMES[0]}" version </dev/null 2>/dev/null || true)
    V2=$(npm view "${PKG_NAMES[1]}" version </dev/null 2>/dev/null || true)
    [[ "$V1" == "0.1.0" && "$V2" == "0.1.0" ]] && break
    warn "registry 还没看全（pacman=${V1:-无} cli=${V2:-无}），第 $round 巡。"
    pause "等半分钟再回车，我重查"
  done
  if [[ "$V1" == "0.1.0" && "$V2" == "0.1.0" ]]; then
    printf '  %s✓ registry 复核通过：@xiechimon/pacman@0.1.0 与 @xiechimon/pacman-cli@0.1.0%s\n' "$GREEN" "$RESET"
  else
    warn "registry 复核未过——发布没成功或没发全；回上一步排查（E401→token，E403→权限/2FA，404→命令没真跑）。"
    SKIPPED+=("registry 复核（两包未齐）")
  fi
else
  warn "前置自检熔断：#261 / #262 的包整形未落地（看上方具体告警行）。"
  SKIPPED+=("首发执行（包整形前置未落地，命令未展示）")
  SKIPPED+=("干净环境 npx 验收（依赖已发布的包）")
  V1="" V2=""
fi

# ── Stage 5: 干净环境 npx 验收（W2-D5 口径）────────────────────────────────
stage "干净环境 npx 验收（临时 HOME 隔离走 npx 全链）"
ACCEPT_HOME=""
if [[ "${V1:-}" == "0.1.0" && "${V2:-}" == "0.1.0" ]]; then
  ACCEPT_PORT=""
  for p in 8791 8792 8793 8794 8795 8796 8797 8798 8799; do
    if ! lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then ACCEPT_PORT="$p"; break; fi
  done
  [[ -z "$ACCEPT_PORT" ]] && ACCEPT_PORT=8791
  note "验收端口 $ACCEPT_PORT（5173/8787 是主仓 dev 栈不动；8390/8399 是别的车道段位）。"
  ACCEPT_HOME=$(mktemp -d "${TMPDIR:-/tmp}/pacman-accept.XXXXXX")
  say "隔离 HOME：$ACCEPT_HOME——npx 缓存、~/.pacman 数据全落在这里，验收后整目录删掉。"
  say "在你自己的终端跑（bash / zsh / fish 通用 env 前缀形态）："
  step "env PORT=$ACCEPT_PORT HOME=$ACCEPT_HOME npx -y @xiechimon/pacman"
  note "冷缓存要下整包 + better-sqlite3 预编译二进制，几十秒属正常；"
  note "Node 22/24 LTS 即装即跑，更新的 major 可能现场编译（W2-D3 已声明）。"
  pause "看到 server 监听日志（或仍在下载）就回车——我这边轮询探测"
  APP_CODE=""
  for _ in $(seq 1 90); do
    APP_CODE=$(curl -s --noproxy '*' -o /dev/null -w '%{http_code}' --max-time 2 "http://127.0.0.1:$ACCEPT_PORT/app" || true)
    [[ "$APP_CODE" == "200" ]] && break
    sleep 2
  done
  if [[ "$APP_CODE" == "200" ]]; then
    printf '  %s✓ GET /app → 200（包内 web dist 托管正常）%s\n' "$GREEN" "$RESET"
  else
    warn "GET /app → ${APP_CODE:-000}：web dist 未进包或 webDir 解析失败（对照 #261 失败方式 2）。"
    SKIPPED+=("npx 验收 /app 200")
  fi
  ME_CODE=$(curl -s --noproxy '*' -o /dev/null -w '%{http_code}' --max-time 5 "http://127.0.0.1:$ACCEPT_PORT/api/user/me" || true)
  if [[ "$ME_CODE" == "200" ]]; then
    printf '  %s✓ GET /api/user/me → 200（seed 用户面正常）%s\n' "$GREEN" "$RESET"
  else
    warn "GET /api/user/me → ${ME_CODE:-000}（对照 #261 失败方式 3：migrate/seed 未进包）。"
    SKIPPED+=("npx 验收 /api/user/me 200")
  fi
  if [[ -f "$ACCEPT_HOME/.pacman/server/server.db" ]]; then
    printf '  %s✓ %s/.pacman/server/server.db 已落盘（首启自动建库）%s\n' "$GREEN" "$ACCEPT_HOME" "$RESET"
  else
    warn "隔离 HOME 下没找到 .pacman/server/server.db——首启建库没跑成。"
    SKIPPED+=("首启建库落盘")
  fi
  say "接着验执行机链（W2-D5 第二段）：网页建 API key → 全局装 cli → enroll。"
  open_url "http://127.0.0.1:$ACCEPT_PORT/app/api-keys"
  step "新建一把 key（名字随意，如 accept），明文只显示一次——复制。"
  step "npm install -g @xiechimon/pacman-cli    # 真实用户路径，落本机全局 prefix"
  step "env HOME=$ACCEPT_HOME pacman start --api-key <粘贴那把key> --server http://127.0.0.1:$ACCEPT_PORT"
  note "pacman start 默认后台化（enroll 完即返回）；机器名默认取 hostname。"
  open_url "http://127.0.0.1:$ACCEPT_PORT/app/resources/machines"
  confirm "机器列表出现你的主机名行了？" || warn "没出现就回终端看 pacman 报错（enroll 401→key 抄错；404→--server 端口不对）"
  say "收尾清理（enroll 验完即可做）："
  step "Ctrl-C 停掉 npx 的 server"
  step "env HOME=$ACCEPT_HOME pacman stop"
  step "npm rm -g @xiechimon/pacman-cli    # 可选——留着就是你机器上的正式 cli"
  if confirm "要我现在删掉隔离目录 $ACCEPT_HOME 吗？"; then
    rm -rf "$ACCEPT_HOME" && note "✓ 已删 $ACCEPT_HOME"
  fi
else
  warn "跳过：两包尚未齐发（registry 不是双 0.1.0）。先回 Stage 4 收尾发布。"
fi

# ── Stage 6: 收尾与事后处置 ───────────────────────────────────────────────
stage "收尾与事后处置"
say "首发 token 用后处置：回 tokens 页删掉首发那枚（尤其走了 All Packages 退路的）；"
say "日常后续发布直接 npm login + OTP 即可，不依赖任何长期 token。"
open_url "https://www.npmjs.com/settings/${NPM_USERNAME}/tokens"
step "Tokens 列表 → 找 pacman-first-publish-0.1.0 → Delete。"
note "本向导没向磁盘写任何凭证（.env / .npmrc 均未动过）；token 随进程消失。"
note "W2 收尾对照：#265 README quickstart 换 npx 形态、#264 CI pack 冒烟、"
note "#266 首发实测记录（本向导的真人首跑就写在 #266 里）。"

finish
