// Generated by scripts/generate-icons.mjs from lucide arrow-down shape (ISC), the registry message-scroller default glyph (#871ac28343, seen 1×: chief stream jump-to-latest button (#1009 A1, MessageScrollerButton children override)). Do not edit.
import type { SVGProps } from 'react';

export function ArrowDown({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M12 5v14" />
      <path d="m19 12-7 7-7-7" />
    </svg>
  );
}
