// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#728b83a852, seen 1×: aria:排序). Do not edit.
import type { SVGProps } from 'react';

export function ArrowUpDown({ width = 13, height = 13, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M7 4v16" />
      <path d="M3 8l4-4 4 4" />
      <path d="M17 20V4" />
      <path d="M13 16l4 4 4-4" />
    </svg>
  );
}
