// Generated by scripts/generate-icons.mjs from docs/research/assets/r6/icons.json (#372d23316f, seen 1×: near:关闭). Do not edit.
import type { SVGProps } from 'react';

export function Ban({ width = 14, height = 14, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="12" cy="12" r="9" />
      <path d="M15.5 8.5 8.5 15.5" />
    </svg>
  );
}
