// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#3b5f1491ac, seen 8×: near:机器 | near:模型服务新建 | near:技能新建). Do not edit.
import type { SVGProps } from 'react';

export function ChevronLeft({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <polyline points="15 18 9 12 15 6" />
    </svg>
  );
}
