// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#ad6a2eb06b, seen 14×: aria:收起项目 | aria:收起项目 | /app/ +dialog:新建任务). Do not edit.
import type { SVGProps } from 'react';

export function ChevronDown({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}
