// Generated by scripts/generate-icons.mjs from a 1:1 trace of the r5 100 bitmap example glyph (lucide folder shape) (#eba87897d3, seen 1×: chief example card 帮我创建一个新项目 (traced from r5 100)). Do not edit.
import type { SVGProps } from 'react';

export function ChiefFolder({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>
  );
}
