// Generated by scripts/generate-icons.mjs from a re-trace of the r5 111 bitmap model-slot glyph: the first trace misread the 10px bitmap stem/bar topology and rendered a "ㅋ" shape; the magnified bitmap shows the pi runtime mark — top bar over two legs (#07b1711ce8, seen 1×: chief model slot glyph (pi runtime mark, re-traced from r5 111)). Do not edit.
import type { SVGProps } from 'react';

export function ChiefPi({ width = 12, height = 12, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      {...props}
    >
      <path d="M4 7h16" />
      <path d="M9 7v13" />
      <path d="M15 7v13" />
    </svg>
  );
}
