// Generated by scripts/generate-icons.mjs from a 1:1 trace of the r5 111 bitmap model-slot glyph (#1b8ea63344, seen 1×: chief model slot glyph (traced from r5 111)). Do not edit.
import type { SVGProps } from 'react';

export function ChiefPi({ width = 12, height = 12, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      {...props}
    >
      <path d="M5 7h11" />
      <path d="M5 12h5" />
      <path d="M14 7v10" />
    </svg>
  );
}
