// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#971dae195e, seen 1×: /app/schedules). Do not edit.
import type { SVGProps } from 'react';

export function ClockThin({ width = 26, height = 26, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.75"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="12" cy="12" r="9" />
      <path d="M12 7v5l3.5 2" />
    </svg>
  );
}
