// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#23a2f466b0, seen 14×: near:定时 | aria:定时 | near:定时). Do not edit.
import type { SVGProps } from 'react';

export function Clock({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="12" cy="12" r="9" />
      <path d="M12 7v5l3.5 2" />
    </svg>
  );
}
