// Generated by scripts/generate-icons.mjs from lucide-static icon `clock` (ISC; D5 replacement of the todos.dev custom mark, #249) (#971dae195e, seen 1×: /app/schedules). Do not edit.
import type { SVGProps } from 'react';

export function ClockThin({ width = 26, height = 26, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.75"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 6v6l4 2" />
    </svg>
  );
}
