// Generated by scripts/generate-icons.mjs from docs/research/assets/r6/icons.json (#341490246d, seen 4×: aria:复制文本 | aria:复制文本 | near:复制链接). Do not edit.
import type { SVGProps } from 'react';

export function Copy({ width = 13, height = 13, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}
