// Generated by scripts/generate-icons.mjs from docs/research/assets/r6/icons.json (#0f28681526, seen 3×: aria:复制任务 | aria:复制任务 | aria:复制任务). Do not edit.
import type { SVGProps } from 'react';

export function CopyPlus({ width = 13, height = 13, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <line x1="15" y1="12" x2="15" y2="18" />
      <line x1="12" y1="15" x2="18" y2="15" />
      <rect x="8" y="8" width="14" height="14" rx="2" ry="2" />
      <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    </svg>
  );
}
