// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#8683c6c434, seen 9×: aria:Xmon Dai | aria:Xmon Dai | aria:Xmon Dai). Do not edit.
import type { SVGProps } from 'react';

export function EllipsisVertical({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="currentColor"
      {...props}
    >
      <circle cx="12" cy="5" r="1.6" />
      <circle cx="12" cy="12" r="1.6" />
      <circle cx="12" cy="19" r="1.6" />
    </svg>
  );
}
