// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#d6cdd1b1ec, seen 1×: near:任务). Do not edit.
import type { SVGProps } from 'react';

export function FileCheck({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M3 5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <path d="M9 12l2 2 4-4" />
    </svg>
  );
}
