// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#504f0bb7cc, seen 5×: aria:方案 | aria:方案 | aria:方案). Do not edit.
import type { SVGProps } from 'react';

export function FileText({ width = 11, height = 11, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <path d="M14 2v6h6" />
      <path d="M8 13h8M8 17h8" />
    </svg>
  );
}
