// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#b91b7c2d90, seen 2×: aria:变更 | aria:变更). Do not edit.
import type { SVGProps } from 'react';

export function GitCommit({ width = 11, height = 11, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="18" cy="18" r="3" />
      <circle cx="6" cy="6" r="3" />
      <path d="M13 6h3a2 2 0 0 1 2 2v7" />
      <path d="M11 18H8a2 2 0 0 1-2-2V9" />
    </svg>
  );
}
