// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#2e2fcbf87d, seen 2×: aria:看板指南 | aria:看板指南). Do not edit.
import type { SVGProps } from 'react';

export function HelpCircle({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>
  );
}
