// Generated by scripts/generate-icons.mjs from a 1:1 trace of the r2 07 bitmap (project routes predate the r7 dump) (#3807356466, seen 1×: project new avatar tile (traced from r2 07)). Do not edit.
import type { SVGProps } from 'react';

export function ImageFrame({ width = 24, height = 24, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <rect x="3" y="3" width="18" height="18" rx="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L3 21" />
    </svg>
  );
}
