// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#f45f81e81c, seen 11×: near:看板 | aria:看板 | near:看板). Do not edit.
import type { SVGProps } from 'react';

export function Kanban({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M6 5v11" />
      <path d="M12 5v6" />
      <path d="M18 5v14" />
    </svg>
  );
}
