// Generated by scripts/generate-icons.mjs from lucide-static icon `key` (ISC; D5 replacement of the todos.dev custom mark, #249) (#38f362e46f, seen 14×: near:密钥 | aria:密钥 | near:密钥). Do not edit.
import type { SVGProps } from 'react';

export function Key({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="m2 21 9.6-9.6" />
      <path d="m7.5 15.5 2.3 2.3a1 1 0 0 1 0 1.4l-2.1 2.1a1 1 0 0 1-1.4 0L4 19" />
      <circle cx="15.5" cy="7.5" r="5.5" />
    </svg>
  );
}
