// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#38f362e46f, seen 11×: near:密钥 | aria:密钥 | near:密钥). Do not edit.
import type { SVGProps } from 'react';

export function Key({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="7.5" cy="15.5" r="4.5" />
      <path d="M10.7 12.3 21 2" />
      <path d="M15 7l3 3" />
    </svg>
  );
}
