// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#4603cd628a, seen 1×: /app/resources/secrets). Do not edit.
import type { SVGProps } from 'react';

export function KeyThin({ width = 26, height = 26, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.75"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="7.5" cy="15.5" r="4.5" />
      <path d="M10.7 12.3 21 2" />
      <path d="M15 7l3 3" />
    </svg>
  );
}
