// Generated by scripts/generate-icons.mjs from a 1:1 trace of the r2 26 bitmap (project routes predate the r7 dump) (#16e8a57b89, seen 1×: project 任务 view toggle (traced from r2 26)). Do not edit.
import type { SVGProps } from 'react';

export function ListLines({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}
