// Generated by scripts/generate-icons.mjs from docs/research/assets/r6/icons.json (#60d7482621, seen 1×: aria:聊天). Do not edit.
import type { SVGProps } from 'react';

export function MessageSquare({ width = 14, height = 14, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
    </svg>
  );
}
