// Generated by scripts/generate-icons.mjs from lucide minus shape (ISC), adopted for ADR 0013 D3 (Multica chat-window minimize) (#67c17e8b62, seen 1×: chief window Minimize button (ADR 0013 D3)). Do not edit.
import type { SVGProps } from 'react';

export function Minus({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M5 12h14" />
    </svg>
  );
}
