// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#4cdc6d192c, seen 1×: aria:展开侧边栏). Do not edit.
import type { SVGProps } from 'react';

export function PanelLeftOpen({ width = 14, height = 14, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <rect x="3" y="3" width="18" height="18" rx="2" />
      <path d="M9 3v18" />
      <path d="m14 9 3 3-3 3" />
    </svg>
  );
}
