// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#976c401b9f, seen 18×: near:新建项目 | near:任务 | near:任务). Do not edit.
import type { SVGProps } from 'react';

export function Plus({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <line x1="12" y1="5" x2="12" y2="19" />
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}
