// Generated by scripts/generate-icons.mjs from the todos.dev providers runtime tab mark (DOM capture 2026-10-02); supersedes the ChiefPi bitmap trace, which misread the 10px r5 111 glyph (#215f8d8f2d, seen 1×: chief model slot runtime mark (pi) | providers runtime tab 内置 (pi)). Do not edit.
import type { SVGProps } from 'react';

export function RuntimePi({ width = 12, height = 12, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="currentColor"
      {...props}
    >
      <path d="M2 2h15v10h-5V7H2ZM2 7h5v5h5v5H7v5H2ZM17 12h5v10h-5Z" />
    </svg>
  );
}
