// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#aeae18a6a1, seen 15×: near:搜索⌘K | aria:搜索 | /app/ ▸搜索面板(⌘K)). Do not edit.
import type { SVGProps } from 'react';

export function Search({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="11" cy="11" r="8" />
      <line x1="21" y1="21" x2="16.65" y2="16.65" />
    </svg>
  );
}
