// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#c5e6f4f29d, seen 10×: aria:安装 App | aria:安装 App | aria:安装 App). Do not edit.
import type { SVGProps } from 'react';

export function Smartphone({ width = 12, height = 12, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <rect x="6" y="2" width="12" height="20" rx="2" />
      <path d="M11 18h2" />
    </svg>
  );
}
