// Generated by scripts/generate-icons.mjs from a 1:1 trace of the r7 28 bitmap (r5b §3.8 records the pill, not its markup) (#025e3a4025, seen 1×: transcript tool pill (traced from r7 28)). Do not edit.
import type { SVGProps } from 'react';

export function Terminal({ width = 12, height = 12, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <polyline points="4 17 10 11 4 5" />
      <line x1="12" x2="20" y1="19" y2="19" />
    </svg>
  );
}
