// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#ec4038d6bd, seen 2×: aria:待开始 | aria:待开始). Do not edit.
import type { SVGProps } from 'react';

export function UnfoldVertical({ width = 13, height = 13, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="m7 20 5-5 5 5" />
      <path d="m7 4 5 5 5-5" />
    </svg>
  );
}
