// Generated by scripts/generate-icons.mjs from a 1:1 trace of the r2 07e bitmap (project routes predate the r7 dump) (#1f4271df3b, seen 1×: project 文件 pane (traced from r2 07e)). Do not edit.
import type { SVGProps } from 'react';

export function Upload({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  );
}
