// Generated by scripts/generate-icons.mjs from lucide-static icon `circle-user` (ISC; D5 replacement of the todos.dev custom mark, #249) (#242f541ee4, seen 1×: near:帐号). Do not edit.
import type { SVGProps } from 'react';

export function UserCircle({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662" />
    </svg>
  );
}
