// Generated by scripts/generate-icons.mjs from docs/research/assets/r7/icons.json (#242f541ee4, seen 1×: near:帐号). Do not edit.
import type { SVGProps } from 'react';

export function UserCircle({ width = 16, height = 16, ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      width={width}
      height={height}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <circle cx="12" cy="8" r="4" />
      <path d="M6 20v-1a6 6 0 0 1 12 0v1" />
    </svg>
  );
}
